config/routes.rb
Rails.application.routes.draw do
  resources :provinces
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root "products#index"

  resources :orders

  resources :products, only: %i[index show] do
    collection do
      get "search", to: "products#search"
    end
  end
  resources :cart do
    post "update_quantity", on: :member
  end
  resources :categories, only: %i[index show]
end

app/views/layouts/components/_nav.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a href="#">
      <img src="/logo.png" width="180" height="180">
    </a>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a href="<%= products_path %>" class="navbar-item">
        Product
      </a>

      <a href="<%= categories_path %>" class="navbar-item">
        Category
      </a>

      <!-- Cart and Orders links -->
      <div class="navbar-item">
        <% if user_signed_in? %>
          <a href="<%= cart_path(current_user.id) %>" class="navbar-item">
            Cart
            <span class="tag is-primary">
              <%= session[:shopping_cart].length %>
            </span>
          </a>
          <a href="<%= orders_path %>" class="navbar-item">
            Orders
          </a>
        <% end %>
      </div>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a href="<%= new_admin_user_session_path %>" class="navbar-item">
            Admin Login
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-item">
      <div class="buttons">
        <%= render partial: 'layouts/components/search_form' %>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <p>Hi, <%= current_user.email.split('@').first %>!</p>
            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'ml-5 button is-danger' %>
          <% else %>
            <%= button_to 'Sign Up', new_user_registration_path, method: :get, class: 'button is-info' %>
            <%= button_to 'Login', new_user_session_path, method: :get, class: 'ml-3 button is-info' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <!-- Add the following code for mobile responsiveness -->
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

      if ($navbarBurgers.length > 0) {
        $navbarBurgers.forEach(function ($el) {
          $el.addEventListener('click', function () {
            const target = $el.dataset.target;
            const $target = document.getElementById(target);

            $el.classList.toggle('is-active');
            $target.classList.toggle('is-active');
          });
        });
      }
    });
  </script>
</nav>

app/views/layouts/components/_search_form.html.erb
<%= form_with(url: search_products_path, method: :get, local: true) do |form| %>
  <div class="field is-grouped">
    <div class="control is-flex is-align-items-center is-space-x-1">
      <div class="field has-addons">
        <div class="control is-relative">
           <%= form.select :category_id, Category.all.collect { |c| [c.name, c.id] }, { include_blank: 'All' }, class: 'select is-border', style: ' margin-top: 10px; padding-top:3px;  height: 40px;' %>

        </div>
      </div>
      <%= form.text_field :keywords, class: "input is-transitioned is-fullwidth is-border is-hover:border-blue-500 margin-top", placeholder: 'Search for Products' %>

     <%= form.submit "Search", class: "button is-primary is-p-2 is-hover:bg-blue-600 is-focus:outline-none is-focus:ring-2 is-focus:ring-blue-300 ", style: 'margin-top: 8px; height: 40px;' %>
    </div>
  </div>
<% end %>