config/routes.rb
Rails.application.routes.draw do
  resources :provinces
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root "products#index"

  resources :orders

  resources :products, only: %i[index show] do
    collection do
      get "search", to: "products#search"
    end
  end
  resources :cart do
    post "update_quantity", on: :member
  end
  resources :categories, only: %i[index show]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<h1 class="title is-2 has-text-weight-bold mb-4 has-text-centered">Categories</h1>
<div class="box is-two-thirds is-relative is-shadow-md is-rounded is-flex is-justify-content-center mx-auto">
    <table class="table is-fullwidth is-size-7 is-text-left has-text-grey-light-dark">
        <thead class="is-size-7 has-text-grey-dark has-background-danger-light">
            <tr>
                <th class="px-6 py-3">
                    Categories
                </th>
                <th class="px-6 py-3">
                    Products in Category
                </th>
            </tr>
        </thead>
        <tbody>
        <% @categories.each do |category| %>
            <tr class="has-background-white-bis has-border-bottom-dark">
                <th class="px-6 py-4 has-text-weight-medium has-text-grey-darkest">
                  <%= link_to category_path(category), class: "has-text-black" do %>
                    <%= category.name %>
                  <% end %>
                </th>
                <td class="px-6 py-4">
                    <%= category.products.count %>
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/categories/show.html.erb
<h1 class="title is-2 has-text-weight-bold mb-4 has-text-centered"><%= @category.name %></h1>
<div class="box is-two-thirds is-relative is-overflow-x-auto is-shadow-md is-rounded is-flex is-justify-content-center mx-auto">
    <table class="table is-fullwidth is-size-7 is-text-left has-text-grey-light-dark">
        <thead class="is-size-7 has-text-grey-dark has-background-danger-light">
            <tr>
                <th class="px-6 py-3">
                    Image
                </th>
                <th class="px-6 py-3">
                    Product Name
                </th>
            </tr>
        </thead>
        <tbody>
        <% @category.products.each do |product| %>
            <tr class="has-background-white-bis has-border-bottom-dark">
                <th class="px-6 py-4 has-text-weight-medium has-text-grey-darkest">
                  <%= link_to product_path(product) do %>
                    <%= image_tag url_for(product.image) %>
                  <% end %>
                </th>
                <td class="px-6 py-4">
                    <%= product.name %>
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>