config/routes.rb
Rails.application.routes.draw do
  resources :provinces
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root "products#index"

  resources :orders

  resources :products, only: %i[index show] do
    collection do
      get "search", to: "products#search"
    end
  end
  resources :cart do
    post "update_quantity", on: :member
  end
  resources :categories, only: %i[index show]
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
  validates :name, presence: true, length: { maximum: 255 }
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  before_action :set_province, only: %i[ show edit update destroy ]

  # GET /provinces or /provinces.json
  def index
    @provinces = Province.all
  end

  # GET /provinces/1 or /provinces/1.json
  def show
  end

  # GET /provinces/new
  def new
    @province = Province.new
  end

  # GET /provinces/1/edit
  def edit
  end

  # POST /provinces or /provinces.json
  def create
    @province = Province.new(province_params)

    respond_to do |format|
      if @province.save
        format.html { redirect_to province_url(@province), notice: "Province was successfully created." }
        format.json { render :show, status: :created, location: @province }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provinces/1 or /provinces/1.json
  def update
    respond_to do |format|
      if @province.update(province_params)
        format.html { redirect_to province_url(@province), notice: "Province was successfully updated." }
        format.json { render :show, status: :ok, location: @province }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1 or /provinces/1.json
  def destroy
    @province.destroy

    respond_to do |format|
      format.html { redirect_to provinces_url, notice: "Province was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_province
      @province = Province.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def province_params
      params.fetch(:province, {})
    end
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/provinces/_form.html.erb
<%= form_with(model: province) do |form| %>
  <% if province.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
        <% province.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/provinces/_province.html.erb
<div id="<%= dom_id province %>">
</div>

app/views/provinces/edit.html.erb
<h1>Editing province</h1>

<%= render "form", province: @province %>

<br>

<div>
  <%= link_to "Show this province", @province %> |
  <%= link_to "Back to provinces", provinces_path %>
</div>

app/views/provinces/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Provinces</h1>

<div id="provinces">
  <% @provinces.each do |province| %>
    <%= render province %>
    <p>
      <%= link_to "Show this province", province %>
    </p>
  <% end %>
</div>

<%= link_to "New province", new_province_path %>

app/views/provinces/new.html.erb
<h1>New province</h1>

<%= render "form", province: @province %>

<br>

<div>
  <%= link_to "Back to provinces", provinces_path %>
</div>

app/views/provinces/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @province %>

<div>
  <%= link_to "Edit this province", edit_province_path(@province) %> |
  <%= link_to "Back to provinces", provinces_path %>

  <%= button_to "Destroy this province", @province, method: :delete %>
</div>