config/routes.rb
Rails.application.routes.draw do
  resources :provinces
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root "products#index"

  resources :orders

  resources :products, only: %i[index show] do
    collection do
      get "search", to: "products#search"
    end
  end
  resources :cart do
    post "update_quantity", on: :member
  end
  resources :categories, only: %i[index show]
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_details
  has_many :orders, through: :order_details
  has_one_attached :image

  validates :name, :price, presence: true, numericality: true
  validates :price, presence: true, numericality: { greater_than: 0 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = case params[:filter]
                when "on_sale"
                  Product.where(on_sale: true)
                when "new"
                  Product.where("created_at >= ?", 3.days.ago)
                when "recently_updated"
                  Product.where("updated_at >= ? AND created_at < ?", 3.days.ago, 3.days.ago)
                else
                  Product.all
                end.page(params[:page]).per(15)
  end

  def show
    @product = Product.find(params[:id])
  end

  def search
    @keywords = params[:keywords]
    @category_id = params[:category_id]

    @products = Product.all

    @products = @products.where("name LIKE ?", "%#{@keywords}%") if @keywords.present?
    return unless @category_id.present? && @category_id != "All"

    @products = @products.where(category_id: @category_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_add_cart.html.erb
  <div class="field is-horizontal mb-10">
            <%= form_with(url: cart_index_path, method: :post) do |form| %>
              <div class="field-body">
                <div class="field">
                  <div class="control">
                    <%= form.hidden_field(:id, value: id) %>
                  </div>
                </div>
                <div class="field">
                  <div class="control">
                    <%= form.number_field(:quantity, value: 1, min: 1, class: 'input') %>
                  </div>
                </div>
                <div class="field">
                  <div class="control">
                    <%= form.button('Add 🛒', type: 'submit', class: 'button is-primary') %>
                  </div>
                </div>
              </div>
            <% end %></div>

app/views/products/index.html.erb
<div class="container is-max-desktop mx-auto px-4">
  <h1 class="title is-2 has-text-centered">Products</h1>
  <div>
    <%= form_with(url: products_path, method: :get, id: 'filter-form') do %>
    <%= select_tag(:filter, options_for_select([['All Products', 'all'], ['On Sale', 'on_sale'], ['New Products', 'new'], ['Recently Updated', 'recently_updated']], params[:filter])) %>
    <%= submit_tag 'Filter' %>
    <% end %>
  </div>
  <div class="is-flex mt-5 is-justify-content-flex-end mb-5">
    <%= paginate @products %><br>
  </div>
  <% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
  <div class="columns is-multiline">
    <% @products.each do |product| %>
      <div class="column is-one-third">
        <div class="card">
          <% if product.image.attached? %>
            <%= link_to product_path(product) do %>
              <%= image_tag url_for(product.image), alt: product.name, class: "card-image-top" %>
            <% end %>
          <% end %>
          <div class="card-content">
            <%= link_to product_path(product) do %>
              <p class="title is-4"><%= product.name %></p>
            <% end %>
            <p class="subtitle is-6 has-text-grey">
              <%= truncate(product.description, length: 100) %>
            </p>
            <p class="has-text-success has-text-weight-bold mb-2">Price: <%= number_to_currency(product.price) %></p>
          </div>
          <%= render partial: 'add_cart', locals: { id: product.id } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/search.html.erb
<div class="container is-max-desktop mx-auto px-4">
  <div class="has-text-centered mt-8 mb-40">
    <h2 class="title is-2 mb-4">Search Results</h2>
    <p class="subtitle is-4 mb-4">Products found when searching for: <%= params[:keywords] %></p>
    <% if @products.empty? %>
      <p class="subtitle is-4 has-text-danger">No products found.</p>
    <% else %>
      <p class="subtitle is-4 mb-4">Results found: <%= @products.count %> products</p>
    <% end %>
  </div>

  <div class="columns is-multiline">
    <% @products.each do |product| %>
      <div class="column is-one-third">
        <div class="card">
          <% if product.image.present? %>
            <%= link_to product_path(product) do %>
              <%= image_tag url_for(product.image), alt: product.name, class: "card-image-top" %>
            <% end %>
          <% end %>

          <div class="card-content">
            <%= link_to product_path(product) do %>
              <h3 class="title is-4 mb-2"><%= product.name %></h3>
            <% end %>
            <p class="subtitle is-6 has-text-grey">
              <%= truncate(product.description, length: 100, separator: ' ') %>
            </p>
            <p class="has-text-success has-text-weight-bold mb-2">Price: $<%= product.price %></p>
             <%= render partial: 'add_cart', locals: { id: product.id } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container is-max-desktop px-4">
  <h1 class="title is-2 has-text-centered">Product Details</h1>

  <div class="columns is-centered">
    <div class="column is-one-third">
      <% if @product.image.present? %>
        <figure class="image is-256x256">
          <%= image_tag @product.image, alt: @product.name %>
        </figure>
      <% end %>
    </div>
    <div class="column is-one-third">
      <h2 class="title is-3 has-text-weight-bold mb-4"><%= @product.name %></h2>
      <p class="mb-4"><strong>Description:</strong> <%= @product.description %></p>
      <p class="mb-4"><strong>Category:</strong> <%= @product.category.name %></p>
      <p class="has-text-success mb-4"><strong>Price:</strong> <%= number_to_currency(@product.price) %></p>
       <%= render partial: 'add_cart', locals: { id: @product.id } %>

      <div class="mt-5">
        <%= link_to(request.referer || products_path, class: "button is-info") do %>
          Go Back
        <% end %>
      </div>
    </div>
  </div>
</div>